CREATE TABLE BOOKLIST(
    BNO NUMBER(8) CONSTRAINT PK_BNO_BL PRIMARY KEY,
    BTITLE VARCHAR(2000),
    WRITER VARCHAR(2000),
    BORROW VARCHAR(50) DEFAULT 'TRUE'
);

COMMENT ON COLUMN BOOKLIST.BNO IS '도서번호';
COMMENT ON COLUMN BOOKLIST.BTITLE IS '도서이름';
COMMENT ON COLUMN BOOKLIST.WRITER IS '저자';
COMMENT ON COLUMN BOOKLIST.BORROW IS '대출여부';
