package com.blue.jdbc_hr;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author Juhong's
 */
public class BookRegistrationJPanel extends javax.swing.JPanel {

Image background=new ImageIcon(("C:\\Users\\mino5\\eclipse-workspace\\JDBC_HR\\src\\푸른하늘도서관 배경.PNG")).getImage();
    
    @Override
    public void paintComponent(Graphics g) {//그리는 함수
       super.paintComponent(g);
       g.drawImage(background, 0, 0, this.getWidth(), this.getHeight(), null);//background를 그려줌      
    }
       /**
        * Creates new form BookRegistrationJPanel
        */
    Handler handler;
	DefaultTableModel BRModel;
	
	
       
    public BookRegistrationJPanel() {
        initComponents();
        //리스너 부착--
        handler = new Handler(this);
        this.btBRAdd.addActionListener(handler);
        this.btBRList.addActionListener(handler);
        this.btBRReset.addActionListener(handler); 
    
    } 
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        //ListBL = new javax.swing.JList<>();
        TableBL=new JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfBtitle = new javax.swing.JTextField();
        tfWriter = new javax.swing.JTextField();
        btBRAdd = new javax.swing.JButton();
        btBRList = new javax.swing.JButton();
        btBRReset = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("HS유지체 ", 1, 36)); // NOI18N
        jLabel1.setText("푸른 하늘 도서관");

        jLabel2.setFont(new java.awt.Font("HS유지체 ", 3, 25)); // NOI18N
        jLabel2.setText("도서등록");

        jLabel3.setFont(new java.awt.Font("HS유지체 ", 3, 18)); // NOI18N
        jLabel3.setText("도서목록");

        jScrollPane1.setViewportView(TableBL);

        jLabel4.setFont(new java.awt.Font("HS유지체 ", 0, 14)); // NOI18N
        jLabel4.setText("도서제목");

        jLabel5.setFont(new java.awt.Font("HS유지체 ", 0, 14)); // NOI18N
        jLabel5.setText("작  가");

        tfBtitle.setFont(new java.awt.Font("Dongle", 0, 14)); // NOI18N
        tfBtitle.setText(" ");
        tfBtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tfWriter.setFont(new java.awt.Font("Dongle", 0, 14)); // NOI18N
        tfWriter.setText(" ");
        tfWriter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btBRAdd.setFont(new java.awt.Font("교보 손글씨 2019", 0, 14)); // NOI18N
        btBRAdd.setText("도서등록");
        btBRAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btBRList.setFont(new java.awt.Font("교보 손글씨 2019", 0, 14)); // NOI18N
        btBRList.setText("목록보기");

        btBRReset.setFont(new java.awt.Font("교보 손글씨 2019", 0, 14)); // NOI18N
        btBRReset.setText("다시쓰기");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3,javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2,javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btBRAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBRList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBRReset))
                            .addComponent(tfWriter)
                            .addComponent(tfBtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfWriter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBRAdd)
                            .addComponent(btBRList)
                            .addComponent(btBRReset))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btBRAdd;
    javax.swing.JButton btBRList;
    javax.swing.JButton btBRReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    //javax.swing.JList<String> ListBL;
    JTable TableBL;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField tfBtitle;
    javax.swing.JTextField tfWriter;
    // End of variables declaration//GEN-END:variables
    String[] title= {"도서번호","도서명","작  가"};
    public void showBLTable(List<VO> arr) {
    	
    	String[][] books=new String[arr.size()][3];
    	if(arr != null) {
    		for(int i=0;i<arr.size();i++) {
    			VO vo=arr.get(i);
    			//String data = vo.getBno() + " " + vo.getBtitle() + " " + vo.getWriter();
   			//BRModel.addElement(data);
    			books[i][0]=vo.getBno()+"";
    			books[i][1]=vo.getBtitle();
    			books[i][2]=vo.getWriter();
    		}
    		this.BRModel = new DefaultTableModel(books, title);
    		this.TableBL.setModel(BRModel);
    	}
		if(arr==null) return;
		Object[] data = new Object[arr.size()];
		for(int i = 0; i < arr.size(); i++) {
			VO emp = arr.get(i);
		}//for---------		
		BRModel = new DefaultTableModel();
  }
  
	public void showBLList(ArrayList<VO> arr) {
				DefaultListModel<String> model=new DefaultListModel<>();
				for(int i=0;i<arr.size();i++) {
					VO vo=arr.get(i);
					String data=vo.getBno()+" "+vo.getBtitle()+" "+vo.getWriter();
					model.addElement(data);
				}
	}
}
