package com.blue.jdbc_hr;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.table.*;

import javax.swing.ImageIcon;

/**
 *
 * @author 82106
 */
public class MbPanel extends javax.swing.JPanel {

	/**
	 * Creates new form MbPanel
	 */
	MbHandler handler;
	DefaultTableModel mbModel;
	String[] title = { "나이", "이름", "주소", "등록날짜", "회원번호"};

	public MbPanel() {
		initComponents();
		this.tfMdate.setEditable(false);
		// 리스너 부착-------------------------
		handler = new MbHandler(this);
		btMbAdd.addActionListener(handler);
		btMbDel.addActionListener(handler);
		btMbEdit.addActionListener(handler);
		btMbList.addActionListener(handler);
		btMbReset.addActionListener(handler);
		
		mbTable.addMouseListener(handler);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		tfMyear = new javax.swing.JTextField();
		tfMname = new javax.swing.JTextField();
		tfMaddress = new javax.swing.JTextField();
		tfMdate = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		btMbAdd = new javax.swing.JButton();
		btMbDel = new javax.swing.JButton();
		btMbEdit = new javax.swing.JButton();
		btMbList = new javax.swing.JButton();
		btMbReset = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		mbTable = new javax.swing.JTable();

		jLabel1.setFont(new java.awt.Font("HS유지체 ", 0, 36)); // NOI18N
		jLabel1.setText("푸른하늘 도서관");

		jLabel2.setFont(new java.awt.Font("HS유지체 ", 0, 24)); // NOI18N
		jLabel2.setText("나이");

		jLabel3.setFont(new java.awt.Font("HS유지체 ", 0, 24)); // NOI18N
		jLabel3.setText("이름");

		jLabel4.setFont(new java.awt.Font("HS유지체 ", 0, 24)); // NOI18N
		jLabel4.setText("주소");

		jLabel5.setFont(new java.awt.Font("HS유지체 ", 0, 24)); // NOI18N
		jLabel5.setText("등록날짜");

		jLabel6.setFont(new java.awt.Font("HS유지체 ", 0, 18)); // NOI18N
		jLabel6.setText("회원관리");

		tfMyear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfMyearActionPerformed(evt);
			}
		});

		tfMname.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfMnameActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("HS유지체 ", 0, 18)); // NOI18N
		jLabel7.setText("회원정보");

		btMbAdd.setFont(new java.awt.Font("HS유지체 ", 0, 15)); // NOI18N
		btMbAdd.setText("회원등록");
		btMbAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btMbAddActionPerformed(evt);
			}
		});

		btMbDel.setFont(new java.awt.Font("HS유지체 ", 0, 15)); // NOI18N
		btMbDel.setText("회원삭제");

		btMbEdit.setFont(new java.awt.Font("HS유지체 ", 0, 15)); // NOI18N
		btMbEdit.setText("회원수정\n");

		btMbList.setFont(new java.awt.Font("HS유지체 ", 0, 15)); // NOI18N
		btMbList.setText("목록보기");
		btMbList.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btMbListActionPerformed(evt);
			}
		});

		btMbReset.setFont(new java.awt.Font("HS유지체 ", 0, 14)); // NOI18N
		btMbReset.setText("다시쓰기");
		btMbReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btMbResetActionPerformed(evt);
			}
		});

		mbTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "나이", "이름", "주소", "등록날짜", "회원번호" }));
		jScrollPane2.setViewportView(mbTable);
		if (mbTable.getColumnModel().getColumnCount() > 0) {
			mbTable.getColumnModel().getColumn(0).setPreferredWidth(40);
		}

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(290, 290, 290).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(36, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
								.createSequentialGroup().addComponent(jLabel6).addGap(142, 142, 142)
								.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(142, 142, 142))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGap(38, 38, 38).addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(tfMyear, javax.swing.GroupLayout.DEFAULT_SIZE,
																240, Short.MAX_VALUE)
														.addComponent(tfMname).addComponent(tfMaddress)
														.addComponent(tfMdate))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
												.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup()
																.addComponent(btMbAdd,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 95,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(btMbDel,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 95,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(btMbEdit,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 95,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(btMbList,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 95,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(39, 39, 39))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																layout.createSequentialGroup().addComponent(btMbReset)
																		.addGap(98, 98, 98)))))
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(30, 30, 30)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(35, 35, 35)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(tfMyear, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(tfMname, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(tfMaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(tfMdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(64, 64, 64)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btMbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btMbDel, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btMbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btMbList, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btMbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										layout.createSequentialGroup().addGap(25, 25, 25)
												.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(87, Short.MAX_VALUE)));
	}// </editor-fold>

	private void tfMnameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void tfMyearActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btMbAddActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btMbListActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btMbResetActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	javax.swing.JButton btMbAdd;
	javax.swing.JButton btMbDel;
	javax.swing.JButton btMbEdit;
	javax.swing.JButton btMbList;
	javax.swing.JButton btMbReset;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane2;
	javax.swing.JTable mbTable;
	javax.swing.JTextField tfMaddress;
	javax.swing.JTextField tfMdate;
	javax.swing.JTextField tfMname;
	javax.swing.JTextField tfMyear;
	// End of variables declaration
	Image background = new ImageIcon(
			("C:\\Users\\mino5\\eclipse-workspace\\JDBC_HR\\src\\푸른하늘도서관 배경.PNG")).getImage();

	@Override
	public void paintComponent(Graphics g) {// 그리는 함수
		super.paintComponent(g);
		g.drawImage(background, 0, 0, this.getWidth(), this.getHeight(), null);// background를 그려줌
	}

	public void showMbTable(List<MbVO> arr) {
		if (arr == null)
			return;
		Object[][] data = new Object[arr.size()][title.length];
		for (int i = 0; i < arr.size(); i++) {
			MbVO mb = arr.get(i);			
			data[i][0] = mb.getMyear();
			data[i][1] = mb.getMname();
			data[i][2] = mb.getMaddress();
			data[i][3] = mb.getMdate();
			data[i][4] = mb.getMnumber();
		} // for-------------------------------------
		mbModel = new DefaultTableModel(data, title);
		mbTable.setModel(mbModel);
	}
	
}
